package html4tree

import org.junit.Test
import org.junit.Assert.*
import java.io.File

class UtilTest {

    @Test
    fun testPushAndPull() {
        val list = LinkedList()

        val file1 = File("file1")
        val file2 = File("file2")
        val file3 = File("file3")

        val entry1 = LinkedListEntry(file1, 1)
        val entry2 = LinkedListEntry(file2, 2)
        val entry3 = LinkedListEntry(file3, 3)

        list.push(entry1)
        list.push(entry2)
        list.push(entry3)

        // It behaves like a queue
        val pulled1 = list.pull()
        assertNotNull(pulled1)
        assertEquals(file1, pulled1?.file)
        assertEquals(1, pulled1?.level)

        val pulled2 = list.pull()
        assertNotNull(pulled2)
        assertEquals(file2, pulled2?.file)
        assertEquals(2, pulled2?.level)

        val pulled3 = list.pull()
        assertNotNull(pulled3)
        assertEquals(file3, pulled3?.file)
        assertEquals(3, pulled3?.level)

        val pulled4 = list.pull()
        assertNull(pulled4)

        // Coverage for getters and setters generated by Kotlin for var
        list.first = null
        assertNull(list.first)
        list.last = null
        assertNull(list.last)
    }

    @Test
    fun testPullEmpty() {
        val list = LinkedList()
        assertNull(list.pull())
    }
}
