package html4tree

import org.junit.Test
import kotlin.test.assertEquals
import kotlin.test.assertNull
import java.io.File

class UtilTest {

    @Test
    fun testLinkedList() {
        val list = LinkedList()

        // Test empty list pull
        assertNull(list.pull())

        // Push single element
        val file1 = File("file1")
        val entry1 = LinkedListEntry(file1, 0)
        list.push(entry1)

        // Pull single element
        val pulled1 = list.pull()
        assertEquals(file1, pulled1?.file)
        assertEquals(0, pulled1?.level)
        assertNull(list.pull()) // Should be empty now

        // Push multiple elements
        val file2 = File("file2")
        val file3 = File("file3")
        list.push(LinkedListEntry(file2, 1))
        list.push(LinkedListEntry(file3, 2))

        // to cover getters for fields first and last (since they are generated by kotlin)
        val l = LinkedList()
        l.first
        l.first = null
        l.last
        l.last = null

        // Test FIFO order
        val pulled2 = list.pull()
        assertEquals(file2, pulled2?.file)
        assertEquals(1, pulled2?.level)

        val pulled3 = list.pull()
        assertEquals(file3, pulled3?.file)
        assertEquals(2, pulled3?.level)

        assertNull(list.pull())
    }
}
